export const GET_GLOBAL_DATA = "GET_COVID_DATA";
export const GET_DATA_ERROR = "GET_COVID_DATA_ERROR";
export const GET_COUNTRY_DATA = "GET_COUUNTRY_DATA";
export const GET_COUNTRY_DATA_ERROR = "GET_COUNRY_DATA_ERROR";
